import FireExtinguisherOutlinedIcon from "@mui/icons-material/FireExtinguisherOutlined";
import AcUnitOutlinedIcon from "@mui/icons-material/AcUnitOutlined";
import SensorsOutlinedIcon from "@mui/icons-material/SensorsOutlined";
import CampaignOutlinedIcon from "@mui/icons-material/CampaignOutlined";
import WaterDropOutlinedIcon from "@mui/icons-material/WaterDropOutlined";
import FireHydrantAltOutlinedIcon from "@mui/icons-material/FireHydrantAltOutlined";
import LightbulbOutlinedIcon from "@mui/icons-material/LightbulbOutlined";
import HealthAndSafetyOutlinedIcon from "@mui/icons-material/HealthAndSafetyOutlined";

const inventoryData = [
  {
    id: 1,
    icon: FireExtinguisherOutlinedIcon,
    iconColor: "#EF4444",
    name: "ABC Fire Extinguisher 4Kg",
    sku: "AFP-EXT-1004",
    category: "Fire Extinguishers",
    warehouse: "Lucknow Central",
    available: 145,
    reserved: 12,
    unitPrice: 1850,
    stockValue: 268250,
    status: "In Stock",
    updated: "2 hrs ago",
  },
  {
    id: 2,
    icon: AcUnitOutlinedIcon,
    iconColor: "#2563EB",
    name: "CO₂ Fire Extinguisher 4.5Kg",
    sku: "AFP-EXT-2045",
    category: "CO₂ Extinguishers",
    warehouse: "Kanpur Hub",
    available: 18,
    reserved: 4,
    unitPrice: 2650,
    stockValue: 47700,
    status: "Low Stock",
    updated: "5 hrs ago",
  },
  {
    id: 3,
    icon: FireExtinguisherOutlinedIcon,
    iconColor: "#F97316",
    name: "Foam Fire Extinguisher 9L",
    sku: "AFP-EXT-3009",
    category: "Foam Extinguishers",
    warehouse: "Noida Depot",
    available: 0,
    reserved: 0,
    unitPrice: 3200,
    stockValue: 0,
    status: "Out of Stock",
    updated: "1 day ago",
  },
  {
    id: 4,
    icon: SensorsOutlinedIcon,
    iconColor: "#8B5CF6",
    name: "Smoke Detector",
    sku: "AFP-SMK-1001",
    category: "Detection Systems",
    warehouse: "Varanasi Store",
    available: 210,
    reserved: 30,
    unitPrice: 980,
    stockValue: 205800,
    status: "In Stock",
    updated: "3 hrs ago",
  },
  {
    id: 5,
    icon: CampaignOutlinedIcon,
    iconColor: "#E11D48",
    name: "Fire Alarm Control Panel",
    sku: "AFP-ALM-2100",
    category: "Fire Alarm",
    warehouse: "Lucknow Central",
    available: 6,
    reserved: 2,
    unitPrice: 18500,
    stockValue: 111000,
    status: "Low Stock",
    updated: "1 day ago",
  },
  {
    id: 6,
    icon: FireHydrantAltOutlinedIcon,
    iconColor: "#0284C7",
    name: "Hydrant Valve 63mm",
    sku: "AFP-HYD-0063",
    category: "Hydrant System",
    warehouse: "Kanpur Hub",
    available: 0,
    reserved: 5,
    unitPrice: 3400,
    stockValue: 0,
    status: "Out of Stock",
    updated: "2 days ago",
  },
  {
    id: 7,
    icon: WaterDropOutlinedIcon,
    iconColor: "#0EA5E9",
    name: "Fire Hose Reel 30m",
    sku: "AFP-HOSE-30",
    category: "Fire Hose",
    warehouse: "Noida Depot",
    available: 54,
    reserved: 45,
    unitPrice: 6200,
    stockValue: 334800,
    status: "Reserved",
    updated: "6 hrs ago",
  },
  {
    id: 8,
    icon: LightbulbOutlinedIcon,
    iconColor: "#EAB308",
    name: "Emergency Exit Light",
    sku: "AFP-LIGHT-01",
    category: "Emergency Lighting",
    warehouse: "Varanasi Store",
    available: 88,
    reserved: 10,
    unitPrice: 1120,
    stockValue: 98560,
    status: "In Stock",
    updated: "4 hrs ago",
  },
  {
    id: 9,
    icon: WaterDropOutlinedIcon,
    iconColor: "#06B6D4",
    name: "Fire Sprinkler Pendant",
    sku: "AFP-SPR-001",
    category: "Sprinkler System",
    warehouse: "Lucknow Central",
    available: 320,
    reserved: 40,
    unitPrice: 145,
    stockValue: 46400,
    status: "In Stock",
    updated: "1 hr ago",
  },
  {
    id: 10,
    icon: HealthAndSafetyOutlinedIcon,
    iconColor: "#22C55E",
    name: "Industrial Safety Helmet",
    sku: "AFP-PPE-101",
    category: "Safety Equipment",
    warehouse: "Kanpur Hub",
    available: 22,
    reserved: 3,
    unitPrice: 420,
    stockValue: 9240,
    status: "Low Stock",
    updated: "8 hrs ago",
  },
];

export default inventoryData;